site_name: xwh_hh's wiki
theme:
  name: material
  language: zh
  features:
    - navigation.tabs        # 这行是重点！启用顶部标签式导航
    - navigation.tabs.sticky # （可选）让顶部导航栏滚动时固定

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  
nav:
  - 首页: index.md
  - 高中数学:
    - 首页: 高数/index.md
  - 数学竞赛: 
    - 首页: 数竞/index.md
    - 代数:
      - 基本不等式: 数竞/基本不等式.md
      - 均值不等式: 数竞/均值.md
      - 柯西不等式: 数竞/柯西.md
      - 柯西不等式衍生物: 数竞/ex柯西.md
    - 几何: 数竞/几何.md
    - 数论: 数竞/数论.md
    - 组合: 数竞/组合.md
  - 大学数学:
    - 首页: 大数/index.md
    - 数学分析 B1: 
      - 简介: 大数/数分1.md
      - 极限: 大数/数分1/极限.md
      - 常用等价小量: 大数/数分1/常用等价小量.md
      - 连续性: 大数/数分1/连续性.md
      - 基本初等函数微积分: 大数/数分1/基本初等函数微积分.md
      - 微分学:
        - 首页: 大数/数分1/微分学.md
        - 函数求导技巧: 大数/数分1/函数求导技巧.md
        - 未定式极限: 大数/数分1/未定式极限.md
        - 单调性、凸性与曲率: 大数/数分1/单调性、凸性与曲率.md
        - Taylor 展开: 大数/数分1/Taylor 展开.md
      - 不定积分:
        - 首页: 大数/数分1/不定积分.md
        - 换元积分法: 大数/数分1/换元积分法.md
        - 分部积分法: 大数/数分1/分部积分法.md
        - 有理函数积分: 大数/数分1/有理函数积分.md
      - 积分学:
        - 首页: 大数/数分1/积分学.md
      - 常微分方程:
        - 首页: 大数/数分1/常微分方程.md
      - 无穷级数:
        - 首页: 大数/数分1/无穷级数.md
  - 高中物理:
    - 首页: 高物/index.md
  - 大学物理:
    - 首页: 大物/index.md
  - 信息竞赛:
    - 首页: 信竞/index.md
    - OI 回忆录: 信竞/OIrecall.md
    - UOJ NOI Round 10 游记: 信竞/unr10.md
  - 杂项:
    - 首页: 杂项/index.md
    - 配置说明: 杂项/配置说明.md
    - 6202 年语文卷: 杂项/6202年OIers统一考试语文.md
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

