site_name: xwh_hh's wiki
theme:
  name: material
  language: zh
  features:
    - navigation.tabs        # 这行是重点！启用顶部标签式导航
    - navigation.tabs.sticky # （可选）让顶部导航栏滚动时固定

nav:
  - 首页: index.md
  - 高中数学: 
    - 首页: 高数/index.md
    - 极限: 高数/极限.md
    - 导数: 高数/导数.md
  - 数学竞赛: 数竞/index.md
  - 大学数学: 大数/index.md
  - 高中物理: 高物/index.md
  - 大学物理: 大物/index.md
  - 信息竞赛: 信竞/index.md
  - 杂项: 杂项/index.md
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
